name: Journey Made
favicon: null
layout_spectrum: 0.09933
typography_spectrum: 0.8010753
title: 'We design meaningful, memorable itineraries '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8893BD'
    - '#424C77'
    - '#010328'
    - '#7E4C02'
    - '#3B2730'
  brandStrength: 0.7956989
  lightness: 0.04348806
  saturation: 0.4413425
  rhythmicContrast: 0.07974643
purpose: []
